- client/public/index.html
- client/src/App.tsx
- client/src/GlobalStyle.tsx
- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
- client/src/containers/Header.tsx
- client/src/pages/ContentList.tsx
- client/src/pages/CountrySelect.tsx
>  ✨ 나라목록 페이지 목업 및 사진 받아오기

- client/src/GlobalStyle.tsx
- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
:lipstick: design : 글로벌 스타일 헤더설정
> :lipstick: design : 글로벌 스타일 헤더설정

- client/src/components/notemodal/NoteModal.tsx
- client/src/pages/CountrySelect.tsx
:lipstick: design : 쪽지모달 스크롤 디자인 추가
> :lipstick: design : 쪽지모달 스크롤 디자인 추가

- server/src/main/java/partypeople/server/review/controller/ReviewController.java
- server/src/main/java/partypeople/server/review/dto/ReviewDto.java
- server/src/main/java/partypeople/server/review/entity/Review.java
- server/src/main/java/partypeople/server/review/mapper/ReviewMapper.java
- server/src/main/java/partypeople/server/review/repository/ReviewRepository.java
- server/src/main/java/partypeople/server/review/service/ReviewService.java
> :sparkles: feat : 평가 등록 구현

- client/src/pages/CountrySelect.tsx
> :sparkles: feat : 나라별 이미지 받기

- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
:lipstick: design : 나라 선택 페이지 스타일 수정
> :lipstick: design : 나라 선택 페이지 스타일 수정

- client/src/components/Main/FourthSection.tsx
- client/src/components/Main/SecondSection.tsx
- client/src/pages/ContinentSelect.tsx
> [Feat/jjm/main] Main page 구현 완료

- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
- client/src/containers/Header.tsx
:lipstick: design : 쪽지 모달 구현 및 스타일
> :lipstick: design : 쪽지 모달 구현 및 스타일

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/notemodal/Message.tsx
- client/src/containers/Header.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/CountrySelect.tsx
:sparkles: feat : 글작성 페이지 및 데이트피커 적용
> :sparkles: feat : 글작성 페이지 및 데이트피커 적용

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
:sparkles: feat : 글작성 성향,테마 태그
> :sparkles: feat : 글작성 성향,테마 태그

- client/src/components/ContentAdd/SearchMap.tsx
:recycle: refactor : 글작성페이지 맵 로드문제해결
> :recycle: refactor : 글작성페이지 맵 로드문제해결

- client/src/pages/ContentEdit.tsx
:lipstick: design : 글수정페이지 디자인
> :lipstick: design : 글수정페이지 디자인

- client/src/pages/CountrySelect.tsx
:lipstick: design : 나라선택페이지 반응형
> :lipstick: design : 나라선택페이지 반응형

- client/src/components/Header/LogoutMenu.tsx
- client/src/components/Header/Menu.tsx
- client/src/containers/Header.tsx
> :lipstick: design : 헤더 반응형 구현

- client/src/containers/Header.tsx
:lipstick: design : 헤더 로그인 로그아웃 상태 수정
> :lipstick: design : 헤더 로그인 로그아웃 상태 수정

- client/src/containers/Header.tsx
:lipstick: design : 로그인 상태 재수정
> :lipstick: design : 로그인 상태 재수정

- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
:lipstick: design : 쪽지사이드바,모달 반응형
> :lipstick: design : 쪽지사이드바,모달 반응형

- server/src/main/java/partypeople/server/message/controller/MessageController.java
- server/src/main/java/partypeople/server/message/dto/MessageDto.java
- server/src/main/java/partypeople/server/message/repository/MessageRepository.java
- server/src/main/java/partypeople/server/message/service/MessageService.java
- server/src/main/java/partypeople/server/message/sse/SseEmitters.java
> :sparkles: feat : 쪽지 수신 알림 뱃지(읽지 않은 쪽지 갯수 전송) 구현

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/pages/ContentAdd.tsx
:sparkles: feat : 지도 위치정보 끌어올리기
> :sparkles: feat : 지도 위치정보 끌어올리기

- server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
- server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
> Feat/hsg/companion 동행글 단건조회 response 데이터 수정

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:sparkles: feat : 글작성페이지 대륙 국가 상태 저장
> :sparkles: feat : 글작성페이지 대륙 국가 상태 저장

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:sparkles: feat : 글작성페이지 대륙, 국가 선택 기능 조정
> :sparkles: feat : 글작성페이지 대륙, 국가 선택 기능 조정

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
✨ feat : 글작성페이지 요청양식작성, 멤버아이디 대륙아이디 수정필요
>  ✨ feat : 글작성페이지 요청양식작성, 멤버아이디 대륙아이디 수정필요

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/pages/CountrySelect.tsx
:sparkles: feat : 나라목록 페이지 랜덤 국가 불러오기 및 반응형 조정/글자수정 필요
> :sparkles: feat : 나라목록 페이지 랜덤 국가 불러오기 및 반응형 조정/글자수정 필요

- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
:sparkles: feat : 쪽지 기능구현 조회,삭제
> :sparkles: feat : 쪽지 기능구현 조회,삭제

- client/package.json
- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
- client/src/components/notemodal/ReadNote.tsx
- client/src/components/notemodal/ReplyNote.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:sparkles: feat : 글작성페이지 요청 및 쪽지 렌더링 및 스타일 정리
> :sparkles: feat : 글작성페이지 요청 및 쪽지 렌더링 및 스타일 정리

- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
- client/src/components/notemodal/ReadNote.tsx
- client/src/components/notemodal/ReplyNote.tsx
:sparkles: feat : 쪽지 최신순 정렬 및 삭제 기능 구현
> :sparkles: feat : 쪽지 최신순 정렬 및 삭제 기능 구현

- client/package.json
- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:sparkles: feat : 지도 마커 위치 주소 변동 추가 및 프록시제거
> :sparkles: feat : 지도 마커 위치 주소 변동 추가 및 프록시제거

- client/src/components/ContentAdd/SearchMap.tsx
:sparkles: feat : 지도 라이브러리속성 리렌더링 방지
> :sparkles: feat : 지도 라이브러리속성 리렌더링 방지

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/containers/Header.tsx
:sparkles: feat : 글작성 멤버아이디 적용 및 로그아웃 로컬스토리지 삭제코드추가
> :sparkles: feat : 글작성 멤버아이디 적용 및 로그아웃 로컬스토리지 삭제코드추가

- client/src/containers/Header.tsx
> :sparkles: feat : 로그인 헤더상태 변경

- client/src/api/customAxios.tsx
- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
:sparkles: feat : 헤더 상태, 글작성페이지 로그인권한부여
> :sparkles: feat : 헤더 상태, 글작성페이지 로그인권한부여

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/notemodal/NoteModal.tsx
:sparkles: feat : 쪽지읽기 권한부여 및 글작성 대륙넘버 고정해제
> :sparkles: feat : 쪽지읽기 권한부여 및 글작성 대륙넘버 고정해제

- client/src/components/notemodal/ReplyNote.tsx
:sparkles: feat : 쪽지 답장 기능 권한부여
> :sparkles: feat : 쪽지 답장 기능 권한부여

- client/src/components/Header/Menu.tsx
- client/src/containers/Header.tsx
> :sparkles: feat : 프로필 라우터설정

- client/src/api/customAxios.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/components/notemodal/Message.tsx
- client/src/components/notemodal/NoteModal.tsx
- client/src/components/notemodal/ReplyNote.tsx
- client/src/containers/Header.tsx
- client/src/pages/ContentEdit.tsx
:sparkles: feat : 로그아웃 메인페이지이동 새로고침
> :sparkles: feat : 로그아웃 메인페이지이동 새로고침

- client/src/pages/ContentEdit.tsx
:sparkles: feat : 수정페이지 요청리팩토링 및 기능완료 구글마커수정필요
> :sparkles: feat : 수정페이지 요청리팩토링 및 기능완료 구글마커수정필요

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentEdit/SearchMap.tsx
:sparkles: feat : 지도 마커 수정 완료, 지도자동렌더 수정필요
> :sparkles: feat : 지도 마커 수정 완료, 지도자동렌더 수정필요

- client/src/containers/Header.tsx
> :sparkles: feat : 실시간 쪽지상태수정

- client/src/containers/Header.tsx
:sparkles: feat : 실시간쪽지 에러처리,조건 수정
> :sparkles: feat : 실시간쪽지 에러처리,조건 수정

- client/src/containers/Header.tsx
> :sparkles: feat : 실시간쪽지개수 최종

- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
- client/src/pages/CountrySelect.tsx
:sparkles: feat : 모달 반응형 높이 및 글작성 태그오류 수정 및 나라페이지 사진 수정
> :sparkles: feat : 모달 반응형 높이 및 글작성 태그오류 수정 및 나라페이지 사진 수정

- server/src/main/java/partypeople/server/review/repository/ReviewRepository.java
- server/src/main/java/partypeople/server/review/service/ReviewService.java
Reverts codestates-seb/seb42_main_008#230
> Revert ":bug: fix : 리뷰한 멤버 조회시 참석하지 않은 회원의 경우 반환되는 데이터 수정"

- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
- client/src/pages/CountrySelect.tsx
:sparkles: feat : 글작성된 나라목록불러오기 및 정렬,디자인, 글작성수정 모달수정 및 이미지 수정
> :sparkles: feat : 글작성된 나라목록불러오기 및 정렬,디자인, 글작성수정 모달수정 및 이미지 수정

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/components/MessageModal/Message.tsx
- client/src/components/MessageModal/NoteModal.tsx
- client/src/components/MessageModal/ReplyNote.tsx
- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
lipstick: design : 알림창디자인 리팩토링
> lipstick: design : 알림창디자인 리팩토링

- client/src/components/ContentEdit/SearchMap.tsx
- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
:lipstick: design : 나라선택페이지 디자인수정
> :lipstick: design : 나라선택페이지 디자인수정

- client/src/pages/CountrySelect.tsx
:lipstick: design : 나라선택페이지 그리드수정
> :lipstick: design : 나라선택페이지 그리드수정

- client/src/components/ContentAdd/SearchMap.tsx
:recycle: refactor : 작성페이지 지도마커수정
> :recycle: refactor : 작성페이지 지도마커수정

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/CountrySelectModal.tsx
- client/src/components/MessageModal/Message.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 글작성페이지로 이동시 대륙국가 받기  및 나라선택페이지 라우트설정
> :recycle: refactor : 글작성페이지로 이동시 대륙국가 받기  및 나라선택페이지 라우트설정

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 글작성 라우팅 완료
> :recycle: refactor : 글작성 라우팅 완료

- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
:recycle: refactor : 글작성 수정시 알림추가
> :recycle: refactor : 글작성 수정시 알림추가

- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:recycle: refactor : 글 작성 수정 페이지에 취소라우터 추가
> :recycle: refactor : 글 작성 수정 페이지에 취소라우터 추가

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/CountrySelectModal.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/components/MessageModal/NoteModal.tsx
- client/src/components/MessageModal/ReadNote.tsx
- client/src/components/MessageModal/ReplyNote.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 모달 디자인 리팩토링 및 기타 디자인 수정
> :recycle: refactor : 모달 디자인 리팩토링 및 기타 디자인 수정

- client/src/components/MessageModal/Message.tsx
- client/src/components/MessageModal/NoteModal.tsx
- client/src/components/MessageModal/ReadNote.tsx
- client/src/components/MessageModal/ReplyNote.tsx
:recycle: refactor : 쪽지 모달 라우터기능 추가, 디자인수정
> :recycle: refactor : 쪽지 모달 라우터기능 추가, 디자인수정

- client/src/pages/CountrySelect.tsx
:recycle: refactor : 나라선택페이지 이미지필터
> :recycle: refactor : 나라선택페이지 이미지필터

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentEdit/CountrySelectModal.tsx
:recycle: refactor :글작성,글수정  국가 검색 기능 추가
> :recycle: refactor : 글작성,글수정  국가 검색 기능 추가

- server/src/main/java/partypeople/server/auth/handler/OAuth2MemberSuccessHandler.java
- server/src/main/java/partypeople/server/member/entity/Member.java
- server/src/main/java/partypeople/server/member/service/MemberService.java
> :recycle: refactor : 구글로그인 비밀번호 메일전송 추가

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/SearchMap.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 글작성수정페이지 성향테마모달 스타일변경 및 제목스타일 변경 등
> :recycle: refactor : 글작성수정페이지 성향테마모달 스타일변경 및 제목스타일 변경 등

- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 글작성수정,나라목록페이지 그림자 추가
> :recycle: refactor : 글작성수정,나라목록페이지 그림자 추가

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/CountrySelectModal.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
- client/src/containers/Header.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 글작성수정페이지 모달높이, 스타일수정
> :recycle: refactor : 글작성수정페이지 모달높이, 스타일수정

- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
- client/src/pages/CountrySelect.tsx
:lipstick: design : 나라목록페이지 호버버튼수정
> :lipstick: design : 나라목록페이지 호버버튼수정

- client/src/components/MessageModal/Message.tsx
- client/src/containers/Header.tsx
:recycle: refactor : 목으로나는 쪽지완성
> :recycle: refactor : 목으로나는 쪽지완성

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentEdit/SearchMap.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:lipstick: design : 글작성수정 페이지 인풋 색 변경
> :lipstick: design : 글작성수정 페이지 인풋 색 변경

- client/src/components/ContentAdd/CountrySelectModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/MessageModal/Message.tsx
- client/src/components/MessageModal/ReadNote.tsx
- client/src/components/MessageModal/ReplyNote.tsx
- client/src/containers/Header.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/CountrySelect.tsx
:recycle: refactor : 헤더 api요청 수정, 전반적인 타입스크립트 수정
> :recycle: refactor : 헤더 api요청 수정, 전반적인 타입스크립트 수정

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentAdd/TendencyModal.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/components/ContentEdit/SearchMap.tsx
- client/src/components/ContentEdit/TendencyModal.tsx
- client/src/components/ContentEdit/ThemeModal.tsx
:recycle: refactor : 모달 x 버튼 추가 및 콘솔정리
> :recycle: refactor : 모달 x 버튼 추가 및 콘솔정리

- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
:lipstick: design : 글작성 및 글수정페이지 에디터 커스텀
> :lipstick: design : 글작성 및 글수정페이지 에디터 커스텀

- client/src/containers/Header.tsx
> :recycle: refactor : 로그아웃 수정

- client/src/components/ContentAdd/SearchMap.tsx
- client/src/components/ContentAdd/ThemeModal.tsx
- client/src/pages/ContentAdd.tsx
:recycle: refactor : 글 작성페이지 타입스크립트 수정완료
> :recycle: refactor : 글 작성페이지 타입스크립트 수정완료

- client/src/components/MessageModal/Message.tsx
- client/src/components/MessageModal/ReplyNote.tsx
- client/src/pages/CountrySelect.tsx
♻️ refactor : 국가 선택페이지 & 쪽지 타입완료
> ♻️ refactor : 국가 선택페이지 & 쪽지 타입완료

- client/src/components/ContentDetail/ContentWriter.tsx
- client/src/components/ContentDetail/SearchMap.tsx
- client/src/components/ContentDetail/Tab/Companion.tsx
- client/src/components/ContentDetail/Tab/Participants.tsx
- client/src/components/ContentDetail/TravelComplete.tsx
- client/src/interfaces/ContentDetail.interface.tsx
- client/src/pages/ContentDetail.tsx
:recycle: refactor : 글세부페이지 타입 완료
> :recycle: refactor : 글세부페이지 타입 완료

- client/src/pages/ContentList.tsx
:recycle: refactor : 글목록페이지 타입완료
> :recycle: refactor : 글목록페이지 타입완료

- client/src/components/ContentDetail/ContentWriter.tsx
:ambulance: !hotfix : 여행완료 상태일 때 수정버튼 비활성화 수정
> :ambulance: !hotfix : 여행완료 상태일 때 수정버튼 비활성화 수정

- client/src/containers/Header.tsx
:recycle: refactor : 새로고침 로그아웃수정
> :recycle: refactor : 새로고침 로그아웃수정

- client/src/containers/Header.tsx
:recycle: refactor : 로그아웃, 쪽지 상태 수정
> :recycle: refactor : 로그아웃, 쪽지 상태 수정

- client/src/containers/Header.tsx
- client/src/pages/ContentAdd.tsx
- client/src/pages/ContentEdit.tsx
♻️ 글 작성,수정 대륙이름 변경 및 쪽지 모달 이벤트 개선, 모달 바깥클릭시 이벤트추가
> ♻️ 글 작성,수정 대륙이름 변경 및 쪽지 모달 이벤트 개선, 모달 바깥클릭시 이벤트추가

- client/src/pages/CountrySelect.tsx
:recycle: refactor : 국가 선택페이지에서 대륙페이지 라우트 추가
> :recycle: refactor : 국가 선택페이지에서 대륙페이지 라우트 추가

- client/src/App.tsx
- client/src/components/Chat/ChatModal.tsx
- client/src/pages/ContentDetail.tsx
:recycle: refactor : 채팅모달통합 및 챗리스트 갱신 문제 해결
> :recycle: refactor : 채팅모달통합 및 챗리스트 갱신 문제 해결
